In [65]:
import numpy as np
from typing import Any, Union

import numpy.typing as npt
import plotly.graph_objects as go

# Part 1

## 1.1 Linear Regression

### Q1

In [62]:
x= np.array([[i]for i in [1,2,3,4]])
print(x, x.shape)

#define x as a column vector

[[1]
 [2]
 [3]
 [4]] (4, 1)


In [63]:
y= np.array([[i]for i in [3,2,0,5]])
print(y, y.shape)

#define y as a column vector

[[3]
 [2]
 [0]
 [5]] (4, 1)


In [67]:
def make_linear_X_matrix(x:"np.ndarray[Any, float]", k:int)->npt.NDArray[float]:
    
    X= np.ones(shape= (x.shape[0], k))

    for col in range(k):
        X[:,col] *= np.power(x[:,0], col)
       
    return X

X= make_linear_X_matrix(x, k=1)

print(X, X.shape)


[[1.]
 [1.]
 [1.]
 [1.]] (4, 1)


In [109]:
def write_equation(k:int, W: 'np.ndarray')->str:

    equation= f'{W[0]:.02f}'

    for x_pow in range(1, k):
        if W[x_pow] < 0:
            equation += f' {W[x_pow]:.02f} x^{x_pow}'
        else:
            equation += f' +{W[x_pow]:.02f} x^{x_pow}'
    return equation

In [117]:
def calculate_MSE(orignal_y:'np.ndarray',
                  predicted_y: 'np.ndarray'
                  )->float:
    
    SE= (orignal_y- predicted_y)
    SSE= np.sum(SE**2)

    MSE= SSE/np.size(orignal_y)

    return MSE


In [118]:

org_pts= go.Figure(data= go.Scatter(x= x[:,0],
                                    y= y[:,0],
                                    mode= 'markers',
                                    hovertemplate= '<br>x=%{x}</br>y=%{y}<extra></extra>'))

org_pts.update_layout(
    title="Data points")
org_pts.show()



for k in range(1,5):
    X= make_linear_X_matrix(x, k= k)
    
    W= np.linalg.inv(X.T@X)@X.T@y


    pts_x= np.linspace(0,6,100, dtype= float).reshape((100, 1))
    pts_X= make_linear_X_matrix(pts_x, k= k)
    pts_y= pts_X@W

    equation = write_equation(k, W[:,0])

    X= make_linear_X_matrix(x, k= k)
    predicted_y= X@W
    
    print(k, equation, calculate_MSE(y[:,0], predicted_y[:,0]))
    

    
    org_pts.add_trace(go.Scatter(x= pts_x[:,0],
                                 y= pts_y[:,0],
                                 name= "k="+str(k),
                                 hovertemplate= f'k={k}'))
    


org_pts.update_layout(title= 'Fitted polynomials',
                      yaxis_range=[-5,8],
                      xaxis_range=[-0,5])

org_pts.show()

1 2.50 3.25
2 1.50 +0.40 x^1 3.0500000000000003
3 9.00 -7.10 x^1 +1.50 x^2 0.8000000000000003
4 -5.00 +15.17 x^1 -8.50 x^2 +1.33 x^3 7.119942986162764e-25


### K-NN

In [13]:
x= np.random.random(size= (100,2))
print(x[::20,:], x.shape)


[[0.80224664 0.01671817]
 [0.46352839 0.70010123]
 [0.16514985 0.85272295]
 [0.71622864 0.59354046]
 [0.62479305 0.49346975]] (100, 2)


In [29]:
y= np.random.randint(0,2, size= (100,1))

print(y[::20,:], y.shape)

[[0]
 [0]
 [0]
 [0]
 [0]] (100, 1)


In [44]:
import numpy as np
import plotly.graph_objects as go

# Define a color map for binary values of y
color_map = {0: 'black', 1: 'red'}

# Create a list of colors based on binary values of y
colors = [color_map[val] for val in y[:, 0]]

# Create a scatter plot
scatter = go.Scatter(x=x[:, 0],
                     y=x[:, 1], 
                     mode='markers', 
                     marker=dict(color=colors),
                     hovertemplate ='<b>X1</b>: %{x:.2f}<br><b>X2</b>: %{y:.2f}<br><extra></extra>',
    )

# Create the layout
layout = go.Layout(title='|S|= 100',
                   xaxis=dict(title='x_1'),
                   yaxis=dict(title='x_2'))

# Create the figure and add the scatter trace
fig = go.Figure(data=[scatter], layout=layout)

# Show the plot
fig.show()


In [89]:
a=12

In [90]:
b=23

In [91]:
c=34

In [92]:
d=34

In [93]:
e=23

In [94]:
f=23